### ISSUE TITLE
启动demo报错，java版本1.8.0_60,启动命令：java -jar sofa-ark-sample-springboot-ark-0.5.0-executable-ark.jar

### ISSUE THREAD

**Issue by itxiaohua** [alipay/sofa-ark#116]
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.sofa.ark Log4j ]
log4j:WARN No appenders could be found for logger (com.alipay.sofa.common.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
starting in sample ark plugin activator
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:108)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:52)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
Caused by: com.alipay.sofa.ark.exception.ArkException: com.alipay.sofa.ark.exception.ArkException: java.lang.reflect.InvocationTargetException
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:79)
        at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:113)
        at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:69)
        ... 8 more
Caused by: com.alipay.sofa.ark.exception.ArkException: java.lang.reflect.InvocationTargetException
        at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:56)
        at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.deploy(BizDeployServiceImpl.java:55)
        at com.alipay.sofa.ark.container.pipeline.DeployBizStage.process(DeployBizStage.java:44)
        at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:73)
        ... 10 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:179)
        at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:52)
        ... 13 more
Caused by: java.lang.RuntimeException: Meet exception when determine whether to start SOFAArk!
        at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:52)
        at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:32)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
        at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:63)
        at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
        at com.alipay.sofa.ark.sample.springbootdemo.SpringbootDemoApplication.main(SpringbootDemoApplication.java:40)
        ... 20 more
Caused by: java.lang.NullPointerException
        at java.lang.String.compareTo(String.java:1155)
        at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.isSpringBoot2(ArkApplicationStartListener.java:64)
        at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:42)
        ... 30 more
stopping in ark plugin activator

**Comment by QilongZhang** [comment]
@itxiaohua  已经修复，参考 https://github.com/alipay/sofa-ark/issues/118
