### ISSUE TITLE
sofa-ark 对java-agent是如何支持的？

### ISSUE THREAD

**Issue by jiangyunpeng** [alipay/sofa-ark#133]
### Your question
我看到 sofa-ark 有一个[AgentClassLoader](https://github.com/alipay/sofa-ark/blob/master/sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/service/classloader/ClassloaderServiceImpl.java#L215) ，但是实际上这个agentClassLoder并不会起到作用。

原因是 java-agent 的premain() 会在sofa-ark初始化之前就执行，这时候sofa的ContainerClassLoder都还没有创建，java-agent 相关的类会被sun.misc.Launcher$AppClassLoader 加载，当应用启动之后在BizClassLoader无法获取到被AppClassLoader 初始化的类，这会导致一些问题，不知道官方有没有解决方案。

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by QilongZhang** [comment]
bizClassLoader 有一段向AgentClassLoader查找类的逻辑；
```java
        // 7. Java Agent ClassLoader for agent problem
        if (clazz == null) {
            clazz = resolveJavaAgentClass(name);
        }
```

**Comment by QilongZhang** [comment]
@jiangyunpeng   这段逻辑是保证BizClassLoader 能够加载到 java agent 中的类，避免出现CNF，类似的场景我们也确实遇到过。你的意思是 Agent 的类在最开始之前已经AppClassLoader加载过一次了，因为BizClassLoader没有委托给 AppClassLoader 加载(暂时没有考虑委托，会引入很多问题)，导致 BizClassLoader 最后加载到的 java agent 类并不是 AppClassLoader 加载的类。这个问题有考虑过的，不过还没有遇到问题。如果你那边有问题，感谢反馈。

**Comment by jiangyunpeng** [comment]
举个栗子， 下面TestAgent 是通过java-agent的方式启动，相对应的类AppContext也是被sun.misc.Launcher$AppClassLoader加载的, 那么在业务代码中获取AppContext.getAppId()是无法获取到正确的id，因为业务代码所属的是bizClassloader。

```
package test;

import java.lang.instrument.Instrumentation;

public class TestAgent {

	public static void premain(String options, Instrumentation inst) {
		System.out.println("begin do premain");
		init();
	}

	public static void init() {
		AppContext.init();
	}
}

package test;

public class AppContext {

	private static String app_id;

	public static String getAppId() {
		return app_id;
	}

	public static void init() {
		app_id = "my-agent";
	}
}

```

就算bizClassLoader向AgentClassLoader查找类也不行，因为两个原因：
1. java-agent 的lib会自动加入到classpath，会直接通过  Biz classpath  加载，不会走到后面的逻辑。
```
		// 6. Biz classpath class
		if (clazz == null) {
			clazz = resolveLocalClass(name);
		}
```
2. 就算不在Biz classpath中 ，createAgentClassLoader方法创建的ClassLoader 是一个parent为null的独立classloader，也不是AppClassLoader，也会存在问题。createAgentClassLoader代码如下：
```
return new URLClassLoader(agentPaths.toArray(new URL[] {}), null);
```
个人认为比较合理的做法是
1. java-agent相关的类应全JVM唯一，遵守双亲委派原则，也就是AgentClassloader的parent设置为SystemClassLoader。
2. java-agent放在Biz classpath之前加载。

**Comment by QilongZhang** [comment]
感谢反馈，回答下你说的问题；

> 就算bizClassLoader委托AgentClassLoader查找类也不行
-----
java agent 不会放入 bizclassloader 的 classpath 中，所以不会出现优先在bizclassloader加载的情况。

> java agent相关的类应全JVM唯一，遵守双亲委派原则，也就是AgentClassLoader的parent设置为SystemClassLoader
-----
agent  不应该以 SystemClasssLoader 为父，特别是在 ide 启动时，SystemClassLoader 会包含很多 classpath, 不仅仅agent的class会被加载，非 agent class 同样也会被加载，所以没有采用这种兜底逻辑。Java agent 相关类是不是全局唯一要看具体的 agent，通常 agent 只是做字节码修改，或者工具类，很少出现状态的记录，你举栗子特殊，因为是不同的classloader 加载，类级别状态会不一致。

解决你说的这种问题，或许可以这样解决，先判断能否通过 agentClasssLoader 加载到，如果能加载到，再通过systemClassLoader 加载。因为内部没有出现过类似的问题，所以只是为了避免CNF， 直接构建 AgentClassLoader 加载了。

**Comment by jiangyunpeng** [comment]
1. 经测试发现在IDE 中启动，java-agent会被自动加入到BizClassPath中的。
2. 因为agent是其他人维护，所以我们无法限定别人带不带状态，实际上，现在很多基于agent来做链路透传的场景，保存状态的情况非常常见，状态还会在多个plugin(spring-mvc,dubbo,mq,tddl)之间修改传递。
3.综合来看，先通过 AgentClasssLoader findClass()如果能find到再委托给SystemClassLoader load是一种比较可行方案。

**Comment by QilongZhang** [comment]
@jiangyunpeng  嗯，可以先通过 AgentClassLoader 尝试加载，成功的话，在委托SystemClassLoader 加载，这个有兴趣欢迎 PR.

> 经测试发现在IDE 中启动，java-agent会被自动加入到BizClassPath中的
----
能否把测试工程上传下，理论上是不会的，除非把agent的包打包放入biz中。

**Comment by jiangyunpeng** [comment]
> @jiangyunpeng 嗯，可以先通过 AgentClassLoader 尝试加载，成功的话，在委托SystemClassLoader 加载，这个有兴趣欢迎 PR.
> 
> > 经测试发现在IDE 中启动，java-agent会被自动加入到BizClassPath中的
> 
> 能否把测试工程上传下，理论上是不会的，除非把agent的包打包放入biz中。

好，我抽空发给你

**Comment by QilongZhang** [comment]
@jiangyunpeng  从我的测试结果来看 https://github.com/QilongZhang/ark-agent-demo，java-agent不会被自动加入到BizClassPath中的.
关于 Agent Class 加载优化「可以先通过 AgentClassLoader 尝试加载，成功的话，在委托SystemClassLoader 加载」已单独issue #134 ， 欢迎PR.

**Comment by jiangyunpeng** [comment]
> @jiangyunpeng 从我的测试结果来看 https://github.com/QilongZhang/ark-agent-demo
> java-agent不会被自动加入到BizClassPath中的.
> 关于 Agent Class 加载优化「可以先通过 AgentClassLoader 尝试加载，成功的话，在委托SystemClassLoader 加载」已单独issue #134 ， 欢迎PR.

1. 我前面说的是在IDE中会，我在你提供的demo上修改为通过ide启动证明确实会被加入到biz classpath，详见：https://github.com/jiangyunpeng/ark-agent-demo

2. 我们这边还有一种情况是通过 com.sun.tools.attach.VirtualMachine 在jvm启动之后动态attach一个jar，这个时候sofa-ark已经初始化完成，AgentClassloader也已经创建完毕，这时会出现cnf问题，貌似这个问题暂时无解，不知道有没有一种机制可以watch到attach事件。

**Comment by QilongZhang** [comment]
@jiangyunpeng  在IDE中，创建BizClassLoader Classpath 有点不一样，稍后修复。

> 我们这边还有一种情况是通过 com.sun.tools.attach.VirtualMachine 在jvm启动之后动态attach一个jar
----
以前解决过类似问题。在使用VirtualMachine挂载agent前，尝试把agent的url反射塞进AgentClassLoader中即可，`java.net.URLClassLoader#addURL`.

另，方便说下你是个人学习还是公司内部在使用SOFAArk?

**Comment by jiangyunpeng** [comment]
> @jiangyunpeng 在IDE中，创建BizClassLoader Classpath 有点不一样，稍后修复。
> 
> > 我们这边还有一种情况是通过 com.sun.tools.attach.VirtualMachine 在jvm启动之后动态attach一个jar
> 
> 以前解决过类似问题。在使用VirtualMachine挂载agent前，尝试把agent的url反射塞进AgentClassLoader中即可，`java.net.URLClassLoader#addURL`.
> 
> 另，方便说下你是个人学习还是公司内部在使用SOFAArk?

我们是公司内部使用

**Comment by QilongZhang** [comment]
@jiangyunpeng  👍  贵司使用 sofa ark 用于解决什么问题，类隔离还是热部署，方便透露兼容问题是哪些吗？如果可以，希望能以 PR 的形式一起完善呢~

**Comment by jiangyunpeng** [comment]
主要是做类隔离解决类冲突的问题，现在兼容性方面主要是和spring的整合，还有一些是我们内部中间件没有考虑到类隔离导致的一些bug，包括dubbo也存在问题：https://github.com/apache/incubator-dubbo/issues/2507
既然来自开源，我们内部完善之后也非常愿意贡献出来。

**Comment by QilongZhang** [comment]
@jiangyunpeng  好的

**Comment by xiaoguoqiang** [comment]
Hi，请教各位大佬。有如下使用情况：
在Biz中，获取agent Jar的路径，并attach到自身JVM中。由于agent jar被打包到了Ark包中，因此获取的agent jar的路径无法load。
逻辑代码如下：
        //get the JAR file path containing the agent.
        ProtectionDomain domain = InstrumentAgent.class.getProtectionDomain();
        CodeSource source = domain.getCodeSource();
        String jarFilePath = new File(source.getLocation().getPath()).getAbsolutePath();

        //获取自身运行的VM
        VirtualMachine vm = getVm();
        vm.loadAgent(jarFilePath, null);
        vm.detach();

上述情况，应该如何解决？

**Comment by QilongZhang** [comment]
@xiaoguoqiang  是否可以单独提个Issue, 并附上 demo。

**Comment by xiaoguoqiang** [comment]
> @xiaoguoqiang 是否可以单独提个Issue, 并附上 demo。

单独提了个Issue，见：https://github.com/alipay/sofa-ark/issues/151

**Comment by Zwl0113** [comment]
我在使用 skywalking 和 sofaboot 的时候遇到了 CNF 的问题 请问有什么解决办法吗 @jiangyunpeng @QilongZhang

**Comment by Zwl0113** [comment]
![image](https://github.com/sofastack/sofa-ark/assets/31676412/eba73d69-e194-4865-953c-6466529f323c)

**Comment by Zwl0113** [comment]
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97)
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:49)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
Caused by: java.lang.ExceptionInInitializerError
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.info(Logger.java:579)
        at com.alipay.sofa.ark.common.log.ArkLogger.info(ArkLogger.java:168)
        at com.alipay.sofa.ark.container.service.ArkServiceContainer.start(ArkServiceContainer.java:75)
        at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:141)
        at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:99)
        ... 8 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at ch.qos.logback.classic.spi.LoggingEvent.<clinit>(LoggingEvent.java)
        ... 15 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:143)
        ... 20 more
Caused by: java.lang.NoClassDefFoundError: org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/ConstructorInter
        at java.base/java.lang.Class.getDeclaredFields0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
        at java.base/java.lang.Class.getDeclaredField(Class.java:2608)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:163)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:234)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:3717)
        ... 25 more
Caused by: java.lang.ClassNotFoundException: org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ConstructorInter
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
        at com.alipay.sofa.ark.bootstrap.ContainerClassLoader.loadClass(ContainerClassLoader.java:42)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 31 more
