### ISSUE TITLE
如果plugin里面包含一个依赖xx.pom，这种打出的插件，启动的时候会报错哎

### ISSUE THREAD

**Issue by lsk569937453** [alipay/sofa-ark#167]
A项目在pom中引用了
<dependency>
			<groupId>xxx.xxx.xxx</groupId>
			<artifactId>webapp.pom</artifactId>
			<version>1.0.6</version>
			<type>pom</type>
</dependency>
然后用sofa-ark-plugin-maven-plugin打成ark插件。
B项目中使用	SofaArkBootstrap.launch(args);启动的时候报错，报错信息如下
###报错信息如下

rkException: Failed to get nested archive for entry lib/webapp.pom-1.0.6.pom
	at com.alipay.sofa.ark.container.pipeline.HandleArchiveStage.process(HandleArchiveStage.java:72)
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:68)
	at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:107)
	at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48)
	at com.alipay.sofa.ark.bootstrap.Launcher.launch(Launcher.java:109)
	at com.alipay.sofa.ark.bootstrap.Launcher.launch(Launcher.java:77)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.remain(SofaArkBootstrap.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.alipay.sofa.ark.support.thread.LaunchRunner.run(LaunchRunner.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Failed to get nested archive for entry lib/webapp.pom-1.0.6.pom
	at com.alipay.sofa.ark.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:106)
	at com.alipay.sofa.ark.loader.JarPluginArchive.getNestedArchive(JarPluginArchive.java:73)
	at com.alipay.sofa.ark.loader.JarPluginArchive.getNestedArchives(JarPluginArchive.java:61)
	at com.alipay.sofa.ark.spi.archive.AbstractArchive.getUrls(AbstractArchive.java:46)
	at com.alipay.sofa.ark.loader.JarPluginArchive.getUrls(JarPluginArchive.java:87)
	at com.alipay.sofa.ark.container.pipeline.HandleArchiveStage.transformPluginArchive(HandleArchiveStage.java:87)
	at com.alipay.sofa.ark.container.pipeline.HandleArchiveStage.process(HandleArchiveStage.java:64)
	... 17 more
Caused by: java.io.IOException: Unable to open nested jar file 'lib/webapp.pom-1.0.6.pom'
	at com.alipay.sofa.ark.loader.jar.JarFile.getNestedJarFile(JarFile.java:242)
	at com.alipay.sofa.ark.loader.jar.JarFile.getNestedJarFile(JarFile.java:229)
	at com.alipay.sofa.ark.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:102)
	... 23 more
### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:0.5.2
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by QilongZhang** [comment]
![image](https://user-images.githubusercontent.com/8833026/50906229-9bcf1800-145f-11e9-8178-c1b76f777e7f.png)

没明白意思，能贴下是怎么引用 webapp.pom 这个文件的吗？

**Comment by QilongZhang** [comment]
@lsk569937453  问题已复现，原因是因为 pom.xml 不是一个 zip/jar 文件导致的。Spring  Boot 目前的做法是不会将非 zip/jar 文件打包，计划也是采用同样策略修复这个问题。 

想知道如果在打包过程中，没有将 pom 文件打入，是否会和你的使用场景产生冲突。
