### ISSUE TITLE
示例工程报错的疑问

### ISSUE THREAD

**Issue by GrayWind33** [alipay/sofa-ark#180]
### Your question

在sample-ark-plugin工程已经install到本地maven仓库后，package sample-springboot-ark也成功了，直接运行sofa-ark-sample-springboot-ark-0.6.0-SNAPSHOT-executable-ark.jar是可以的，但如果是在ide中尝试运行的话，会报错
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred while running. null
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.launch(SofaArkBootstrap.java:59)
	at com.alipay.sofa.ark.sample.springbootdemo.SpringbootDemoApplication.main(SpringbootDemoApplication.java:41)
Caused by: java.lang.RuntimeException: An exception occurred while running. null
	at com.alipay.sofa.ark.support.thread.IsolatedThreadGroup.rethrowUncaughtException(IsolatedThreadGroup.java:50)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.launch(SofaArkBootstrap.java:55)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.ark.support.thread.LaunchRunner.run(LaunchRunner.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.alipay.sofa.ark.exception.ArkException: No Ark Container Jar File Found.
	at com.alipay.sofa.ark.bootstrap.ClasspathLauncher$ClassPathArchive.getContainerArchive(ClasspathLauncher.java:103)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.getContainerArchive(AbstractLauncher.java:120)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:60)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.remain(SofaArkBootstrap.java:82)
	... 6 more
请问是启动参数有问题吗？刚接触这个项目不是很了解，从顺着README和wiki操作没有找到问题，麻烦帮忙解答一下，谢谢

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by QilongZhang** [comment]
在 IDEA 中需要添加依赖:
```xml
<dependency>
    <groupId>com.alipay.sofa</groupId>
    <artifactId>sofa-ark-springboot-starter</artifactId>
</dependency>
```

**Comment by GrayWind33** [comment]
> 在 IDE 中需要添加依赖:
> 
> ```
> <dependency>
>     <groupId>com.alipay.sofa</groupId>
>     <artifactId>sofa-ark-springboot-starter</artifactId>
> </dependency>
> ```

这个在示例中已经有了，SpringbootDemoApplication中也加了SofaArkBootstrap.launch(args)。

**Comment by QilongZhang** [comment]
`SpringbootDemoApplication中也加了SofaArkBootstrap.launch(args) `
这句话不需要加。

**Comment by cnodin** [comment]
我也碰到这样的问题，好像并没有解决啊
