### ISSUE TITLE
No Ark Container jar file found error during running sample from IDE(spring boot or java app)

### ISSUE THREAD

**Issue by July-G** [alipay/sofa-ark#81]
### Describe the bug
When running sample `sofa-ark-sample-springboot-ark` from IDE,

```
Caused by: com.alipay.sofa.ark.exception.ArkException: No Ark Container Jar File Found.
	at com.alipay.sofa.ark.bootstrap.ClasspathLauncher$ClassPathArchive.getContainerArchive(ClasspathLauncher.java:102)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.getContainerArchive(AbstractLauncher.java:131)
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:62)
	at com.alipay.sofa.ark.support.startup.SofaArkBootstrap.remain(SofaArkBootstrap.java:81)
	... 6 more
```

after I  add

       
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-ark-container</artifactId>
            <version>0.5.0-SNAPSHOT</version>
        </dependency>
     
to the pom of `sofa-ark-sample-springboot-ark ` everything seem work fine.

### Environment

- SOFAArk version: 0.5.0-SNAPSHOT
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): Win10
- Maven version:3.5
- IDE version: IDEA2018

**Comment by QilongZhang** [comment]
Actually, i have add the following dependency:
```xml
<dependency>
     <groupId>com.alipay.sofa</groupId>
      <artifactId>sofa-ark-springboot-starter</artifactId>
</dependency>
```
it will import the `sofa-ark-container` indirect，it seems impossible about your doubt~
